### ISSUE TITLE
Concurrent: WinToets

### ISSUE THREAD

**Issue by ariep** [dporru/tribble#1]
Ilja (broer van Jelske, middelbare-schooldocent wiskunde) wees me op het bestaan van [WinToets](http://www.drp.nl/wintoets/):

> WinToets 4 is een uitgebreid pakket programma's voor het beheren van toetsenbanken, voor het digitaal toetsen en voor het beheren van toetsen die moeten worden afgedrukt of geëxporteerd moeten worden naar een elektronische omgeving, website, stemkastjes, Quayn en DigiBorden. U leert u er in een paar uur mee werken. Hiervoor hebben we cursusboeken voor starters beschikbaar. Het wintoets-toetsformaat is het defacto standaard formaat in Nederland voor toetsenbanken.

Ik heb het nog niet goed bekeken, maar het lijkt wel relevant.

**Comment by dporru** [comment]
Vooral [quayn](http://www.drp.nl/wintoets/index.php?pageId=1553) lijkt een directe concurrent. Dat formaat is in ieder geval iets wat we zouden moeten ondersteunen.
