### ISSUE TITLE
Gebruikers & inloggen

### ISSUE THREAD

**Issue by ariep** [dporru/tribble#18]
OAuth2

**Comment by ariep** [comment]
Het inlogsysteem werkt nu. Iedere persoon met een google-account kan inloggen; misschien willen we dit later wel beperken.

De toetsen en vragen zijn nog wel gezamenlijk voor alle gebruikers. Voor nu leek me dat het beste i.v.m. Loeks samenwerking met zijn collega; dan hoeven we nog niet iets met delen van toetsen/vragen te doen.

Willen we wel aparte gegevens per gebruiker voor de demoversie?

**Comment by dporru** [comment]
Lijkt me beter om de vragen toch per gebruiker te houden, dan is het makkelijker iemand een demo account te laten maken. Voor delen zou je een gmail account kunnen delen.

Wat ook zou kunnen is wat logica in de server maken om accounts 'aan elkaar te koppelen'. Dat zou iets zijn wat je dan alleen via de command-line kunt instellen (of settings?).

**Comment by ariep** [comment]
In het configuratiebestand kun je nu gebruikers koppelen aan accounts:

```
accounts=[("109910513906856926521","arietest"),("01234567890123456789","anderVoorbeeldAccount")]
```

"accounts" is een lijst van paren van strings: links je google-ID, en rechts de naam van het account (willekeurige string). Als meerdere id's hier hetzelfde account hebben, delen die gebruikers dus samen een set toetsen en vragen.

Je google-ID kun je vinden door te proberen in te loggen terwijl je nog geen account hebt, dan verschijnt je google-ID in beeld.

**Comment by dporru** [comment]
De client laat nu een inlogscherm zien met een knop die naar Google verwijst. 

Commit ee9267d36cb5cb85f26e8633b5f125eb988cd290
