### ISSUE TITLE
invoeren vragen met meer dan platte tekst.

### ISSUE THREAD

**Issue by LoekSpitz** [dporru/tribble#3]
Arie gaf al aan dat hij nu latex gebruikt om vragen in te voeren. Ik denk dat we die optie willen houden, maar ook voor minder tex-vaardige mensen moet het naturlijk mogelijk zijn om vragen anders dan platte tekst in te voeren. Wat voor opmaakmogelijkheden willen we meegeven?
- schuin, dik drukken
- tabel invoegen
- wiskundige symbolen (integraal, breuk etc? wordt al snel een rommeltje)
- plaatjes (maar daar maak ik wel een appart issue van
- gekleurde tekst?

**Comment by dporru** [comment]
We zouden hier naast latex ook iets als markdown kunnen ondersteunen. 
Maar voor de meeste gebruikers zou je een wysiwyg editor willen. Dan kom 
je al snel op html output, wat op zich geen probleem hoeft te zijn. 
Misschien is het een idee om de vragen altijd in html te doen en aan de 
client kant de conversie naar html te doen.

Ik zou beginnen met een wysiwyg editor en geavanceerdere opties later 
toevoegen, ook afhankelijk van de vraag er naar.

LoekSpitz schreef op 07-05-15 om 13:53:

**Comment by dporru** [comment]
Het client gedeelte hiervan werkt nu. 
17d40deacb1ec1bfb5763a658b8cf58319e720be

**Comment by ariep** [comment]
Dit werkt nu helemaal: de html-invoer van de gebruiker wordt door de server ingelezen en omgezet in Pandoc (Haskell-library die conversie biedt tussen allerlei tekstformaten). De opmaak blijft daardoor behouden bij het exporteren van de toets.

Dit is overigens in de branch "html", die ik nog niet naar master heb gemerged: de centrale datatypes (toets, vraag, etc.) zijn veranderd, dus als we bestaande toetsen willen behouden moet ik wat migratiecode schrijven. Dit heb ik nog niet gedaan, omdat het wat extra werk is. @LoekSpitz, hoeveel vragen heb je al ingevoerd?
