### ISSUE TITLE
Slimmer afbreken van vraagtitels in vragenlijst.

### ISSUE THREAD

**Issue by dporru** [dporru/tribble#35]
Bijvoorbeeld voor een nieuw html blok.

**Comment by ariep** [comment]
De vraag wordt nu op de server automatisch afgebroken om de titel van de vraag te vormen. Dit afbreken is nu nog niet zo slim, maar kan makkelijk verbeterd worden.

Meld hier gevallen waarin het afbreken niet mooi is, dan gebruik ik die om het te verbeteren.

Verder is de server voorbereid op een aparte titel die je als gebruiker in kunt voeren, voor als het begin van de vraag zelf niet geschikt is als titel. Hier moet nog wel client-code voor geschreven worden.

**Comment by dporru** [comment]
Front-end code moet hier nog voor aangepast worden
