### ISSUE TITLE
Plaatjes invoeren

### ISSUE THREAD

**Issue by LoekSpitz** [dporru/tribble#4]
Het is belangrijk dat we ook de mogelijkheid geven om plaatjes in te voeren. Een optie zou zijn om plaatjes los, dus apart van de vragen in te voeren. Het zou denk ik beter zijn als we een goede manier kunnen vinden om plaatjes in te voeren binnen een vraag. Ik kan me overigens voorstellen dat dit een ramp wordt met exporteren: waar gaat die het plaatje neerzetten, en vooral, wat als de gebruiker niet blij is met de keuze van het exportprogramma. Kunnen we er voor zorgen dat het dan nog aanpasbaar is? Ik neem aan van niet bij bijvoorbeeld pdf...

**Comment by ariep** [comment]
Na het uploaden van een plaatje moet de server een stukje JSON sturen:
https://github.com/Alex-D/Trumbowyg/blob/master/plugins/upload/trumbowyg.upload.php
