### ISSUE TITLE
Multiple choice: na export is nog steeds antwoord A altijd goed

### ISSUE THREAD

**Issue by LoekSpitz** [dporru/tribble#43]
Mooi is natuurlijk als er verschillende manieren zijn om te bepalen in welke volgorde antwoorden verschijnen, maar minimaal nodig is dat ze random worden gehusseld.

**Comment by ariep** [comment]
Ja klopt, de server kreeg van de client ongeschikte volgorde-informatie (bv. de lijst [0,1,2,3] terwijl er maar drie opties waren), dus voor nu heb ik maar even een vaste volgorde aangehouden.

Loek, hoe zou je dit het liefste willen kunnen instellen? Met een extra instelling (random, lengte van antwoord, handmatig) per toets (of account?) die wordt onthouden, of een keuze tussen die opties op het moment dat je exporteert, of nog anders?

**Comment by dporru** [comment]
De client geeft nu wel juiste data door.
