### ISSUE TITLE
Voorgestelde naam bij export is nu toetsnaam, ik denk dat Toets.toetsnaam en Antwoorden.toetsnaam beter zijn

### ISSUE THREAD

**Issue by LoekSpitz** [dporru/tribble#44]
Verder merk ik dat ik als ik vanuit chrome exporteer ik er voor moet zorgen dat er niet al een bestand met dezelfde naam bestaat, dan krijg ik 'download error', ook al vraagt hij eerst of ik het bestand wil overschrijven. Waarschijnlijk is dit een issue van de browser of van het besturingsysteem, maar wilde het toch genoemd hebben. Als je vaak dezelfde toets exporteert is het best wel onhandig.

**Comment by dporru** [comment]
Ik kan de download error niet reproduceren. Klinkt eerder als een instelling die verkeerd staat.
