### ISSUE TITLE
zoeken naar vragen

### ISSUE THREAD

**Issue by LoekSpitz** [dporru/tribble#9]
Als ik naar de huidige schermindeling kijk, kan ik me voorstellen dat op het moment dat je naar vragen aan het zoeken bent die je al eerder hebt gemaakt, het handig zou zijn daar een groter deel van het scherm voor te gebruiken. Ik zou in de praktijk moeten zien hoe dat gaat. Ik denk dat de schermindeling nu wel goed is voor het invoeren; dat is waar de nadruk op moet liggen, zeker voor nieuwe gebruikers, en dat neemt nu ook het grootste gedeelte in.

**Comment by ariep** [comment]
Voor nu werkt dit (al een tijdje). Laten we dit heropenen op het moment dat duidelijk is wat er verbeterd moet worden.
